name: CI of mc_int_obj_description

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, ubuntu-24.04]
        variant: [ROS, Standalone]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v6
      if: ${{ matrix.variant == 'Standalone' }}
      with:
        submodules: recursive
    - name: Build standalone
      if: ${{ matrix.variant == 'Standalone' }}
      uses: jrl-umi3218/github-actions/build-cmake-project@master
      with:
        options: -DDISABLE_ROS=ON
    - name: Build with colcon
      uses: jrl-umi3218/github-actions/build-colcon-project@master
